# fly.toml app configuration file generated for protohackers-aged-glade-647 on 2024-09-13T19:20:33-03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'protohackers-aged-glade-647'
primary_region = 'gru'

[experimental]
  auto_rollback = true

[build]

[env]
  LOG_LEVEL = 'debug'
  TCP_PORT = '5000'
  UDP_PORT = '6000'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[services]]
internal_port = 5001
protocol = "tcp"

[[services.ports]]
handlers = []
port = 5001

[[services]]
internal_port = 5002
protocol = "tcp"

[[services.ports]]
handlers = []
port = 5002

[[services]]
internal_port = 5003
protocol = "tcp"

[[services.ports]]
handlers = []
port = 5003

[[services]]
internal_port = 5004
protocol = "tcp"

[[services.ports]]
handlers = []
port = 5004

[[services]]
  protocol = 'udp'
  internal_port = 6000

  [[services.ports]]
    port = 6000

  [services.concurrency]
    type = 'connections'
    hard_limit = 250
    soft_limit = 200

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
